server:
  port: 8083

spring:
  application:
    name: player-profile-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"